id: IE878BF7B
legacy_id: P006693
ocr_import_info:
  bdrc_scan_id: W14425
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T10:29:55'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T13:44:02.424856+00:00'
last_modified: 2022-08-29 21:44:32.263663
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W14425
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW14425
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་ཀླུ་སྒྲུབ་དགོངས་རྒྱན་གྱི་དགག་པ།
  author: ཛེ་སྨད་བློ་བཟང་དཔལ་ལྡན་བསྟན་འཛིན་ཡར་རྒྱས།
statistics:
  ocr_word_mean_confidence_index: 0.8682877835355504
  ocr_word_median_confidence_index: 0.9300000071525574
quality: null
bases:
  I1KG9840:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9840
      total_pages: 210
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9840.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.8682877835355504
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
