id: IE878BF7B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T10:31:18+00:00'
last_modified: '2022-06-08T06:11:33.507163+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W14425
  title: དབུ་མ་ཀླུ་སྒྲུབ་དགོངས་རྒྱན་གྱི་དགག་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1CE4:
      image_group_id: I1KG9840
      title: ''
      total_pages: 210
      order: 1
      base_file: 1CE4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
